---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: xray-client
  labels:
    app: xray-client
spec:
  type: NodePort
  selector:
    app: xray-client
  ports:
    - name: sock
      nodePort: 31080
      port: 1080
      protocol: TCP
      targetPort: 1080
    - name: http
      nodePort: 31081
      port: 1081
      protocol: TCP
      targetPort: 1081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: xray-client
  labels:
    app: xray-client
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: xray-client
  template:
    metadata:
      labels:
        app: xray-client
    spec:
      containers:
        - name: xray-client
          image: ccr.ccs.tencentyun.com/fastapp/xray-client:v1.0.0.3.211df6a
          command:
            - /opt/apps/xray/xray
            - -c
            - /opt/apps/xray/config.json
          resources:
            limits:
              cpu: 500m
              memory: 1G
            requests:
              cpu: 500m
              memory: "256Mi"

