---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    app: chatgpt-web

---
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: apps
  name: chatgpt-web-cm
  labels:
    app: chatgpt-web
data:
  config.json: |
    {
      "api_key": "sk-",
      "api_url": "",
      "port": 8080,
      "listen": "",
      "bot_desc": "你是一个AI助手，我需要你模拟一名温柔贴心的女助理来回答我的问题。",
      "proxy": "socks5://xray-client.apps:1080",
      "model": "gpt-3.5-turbo",
      "max_tokens": 3000,
      "temperature": 0.9,
      "top_p": 1,
      "frequency_penalty": 0.0,
      "presence_penalty": 0.6,
      "auth_user": "admin",
      "auth_password": "123456"
    }


---
apiVersion: v1
kind: Service
metadata:
  namespace: apps
  name: chatgpt-web
  labels:
    app: chatgpt-web
spec:
  type: NodePort
  selector:
    app: chatgpt-web
  ports:
    - name: http
      nodePort: 30999
      port: 8080
      protocol: TCP
      targetPort: 8080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: apps
  name: chatgpt-web
  labels:
    app: chatgpt-web
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: chatgpt-web
  template:
    metadata:
      labels:
        app: chatgpt-web
    spec:
      containers:
        - name: chatgpt-web
          image: ccr.ccs.tencentyun.com/fastapp/chatgpt-web:v1.0.0.85.057548d
          env:
            - name: APIKEY
              value: "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"
          command:
            - /opt/apps/chatgpt-web
          volumeMounts:
            - name: config-vol
              mountPath: /opt/apps/config.json
              subPath: config.json
            - name: data-vol
              mountPath: /opt/apps/data
          resources:
            limits:
              cpu: 500m
              memory: 1G
            requests:
              cpu: 500m
              memory: "256Mi"
      volumes:
        - name: data-vol
          hostPath:
            path: /data
        - name: config-vol
          configMap:
            name: chatgpt-web-cm
            items:
              - key: config.json
                path: config.json

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: apps
  name: chatgpt-web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
    nginx.ingress.kubernetes.io/ssl-passthrough: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  tls:
    - secretName: chatgpt-web-tls
      hosts:
        - ai.bgton.cn
  rules:
    - host: ai.bgton.cn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatgpt-web
                port:
                  number: 8080
